name: Daily Strategy Email

on:
  schedule:
    - cron: "30 6 * * *"  # Run every day at 06:30 UTC
  workflow_dispatch:      # Allow manual trigger from GitHub UI

jobs:
  run-strategy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trade validator
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python ai_trade_validator.py
